---
- name: Download activemq
  hosts: localhost
  tasks:
   - name: Create a Directory /opt/activemq
     become: yes
     file:
       path: /opt/activemq
       state: directory
       mode: 0755
       owner: pjishnu
       group: pjishnu

- name: download activemq
  hosts: localhost
  tasks:
    - name: Download activemq
      get_url:
        url: https://dlcdn.apache.org/activemq/5.16.3/apache-activemq-5.16.3-bin.tar.gz
        dest: /opt/activemq
        mode: 0755
