---
- name: download activemq
  hosts: localhost
  tasks:
    - name: Download activemq from a remote_src
      get_url:
        url: https://dlcdn.apache.org/activemq/5.16.3/apache-activemq-5.16.3-bin.tar.gz
        dest: /tmp/activemq
        mode: 0755

- name: Unarchive activemq
  hosts: localhost
  tasks:
    - name: Unarchive downloaded activemq.tar into /opt
      unarchive:
        src: /tmp/activemq/apache-activemq-5.16.3-bin.tar.gz
        dest: /opt/activemq
        remote_src: yes
